### ISSUE TITLE
Drag selection in JXMonthView behaves differently from bottom to top

### ISSUE THREAD

**Issue by bugabinga** [isp-insoft-gmbh/SwingX#15]
When selecting weeks from top to bottom it extends the selection week by week (Monday to sunday).
Clicking a single week selects the whole week (Monday to sunday). However, when drag selecting from bottom to top, it selects from Monday of the bottom week to Sunday of the top week.

**Comment by Bios-Marcel** [comment]
Fixed in 4b7b8fd8de42f6b8794530a24414d51b62e0336f
